### ISSUE TITLE
Error on .NET Standard 1.6

### ISSUE THREAD

**Issue by emdadgar2** [ArxOne/MrAdvice#110]
Hi,
1. Create new .Net Standard Class Library project
2. Add MrAdvice 2.5.4 package.
3. Compile and got this error:

Error	MSB4036	The "MrAdviceTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" directory.	ClassLibrary1	C:\Users\xxxxx\.nuget\packages\mradvice\2.5.4\build\MrAdvice.targets	5	

Thanks anyway

**Comment by emdadgar2** [comment]
[ClassLibrary1.zip](https://github.com/ArxOne/MrAdvice/files/1123112/ClassLibrary1.zip)

**Comment by picrap** [comment]
Hi,

I don't have the same problem. I use VS 2017. The task starts, but Mr Advice does not support the portable pdb format (this is related to dnlib, a third-party library). So to make the project build I only had to change the pdb format to full instead of portable.
Could you tell me more about your environment?

Thanks.

**Comment by emdadgar2** [comment]
Hi,
Solved! Thanks.

Please make this note in project main page to save users time.

Thanks again.

**Comment by picrap** [comment]
Was it the PDB format?

**Comment by emdadgar2** [comment]
It was portable format. After change to full format, solved!

Thanks anyway
