### ISSUE TITLE
Documentation, Samples?

### ISSUE THREAD

**Issue by db-007** [ArxOne/MrAdvice#122]
I seem not to be any anything more than couple of sentences?

**Comment by picrap** [comment]
If you need samples and documentation:
* samples can be found in unit tests (sure, they're not documented) which are supposed to cover all features
* documentation can be found here: https://github.com/ArxOne/MrAdvice/wiki/Documentation

All of this is thin, because Mr Advice tries to stay lightweight 😉

**Comment by TheXenocide** [comment]
I have been wanting to get back to improving the XML documentation alongside the source, but it seems my life has had other plans plus I have no shortage of side projects. Still following updates and such though, thought I'd let you know I'm still alive and hoping I get the time and motivation to get back into this.

**Comment by picrap** [comment]
That's something I can totally understand, since it's the same for me 😄
