### ISSUE TITLE
Cann't Advice Main method

### ISSUE THREAD

**Issue by mshami85** [ArxOne/MrAdvice#131]
Hi, I've to make an attribute for main() just like 
```
[logged]
static void main()
{
// etc 
}
```

but the property not working( cannot log).

is it a bug or it is not supported for static methods or what?

**Comment by picrap** [comment]
Hi,

That's a good question, I did not test that :) This is possible because the entry point also may have to be changed when weaving the `main` method, which currently is not done.
I'll check that and let you know.
Until then, of course, you can simply do:
```csharp
static void Main() => Main2();

[logger]
static void Main2()
{
   // etc.
}
```

All other static methods are supported (you should just try 😉)

**Comment by picrap** [comment]
I tested it (finally), and I just confirm that it works, the `Main()` is advisable, as every other method.
