### ISSUE TITLE
Allow to collect members dependencies tree

### ISSUE THREAD

**Issue by picrap** [ArxOne/MrAdvice#77]
Allow (by attribute?) to collect methods, fields and properties used by a given method.  
Optionnally make this collect recursive in weaved assembly.  
Inject this as static data in weaved assembly (and keep it small!).

**Comment by TheXenocide** [comment]
Curious to see what you have planned here. I've found myself wanting an attribute that could have a static member/method for retrieving a list of all types/members/assemblies that it is applied to; of course it's possible with reflection, but slow when you ask the question backwards like this sense you have to check every loaded type. I'm not sure if what you're thinking would be able to provide the same kind of functionality, but it would be nice to have something like `public MethodInfo[] GetAppliedMethods()` or for Properties, etc. Also, I've seen Dependency Injection scenarios that use attributes with optional name parameters to initialize IoC containers, like:

    [RegisteredService(typeof(IContract))]
    public class ContractImplementation : IContract { ... }

or, with named service categories, like

    [RegisterService(typeof(IContract), Name="UnitTest")]
    public class TestContract : IContract { ... }

which I've seen used at runtime, but would probably go much faster if they were reflected at build time and then you could do something like `Type[] svcs = RegisterServiceAttribute.GetServices<T>()`, `Type svc = RegisterServiceAttribute.GetService<T>(name: "UnitTest")`, and so on. I see you're thinking more dependency graphs, but I suspect these amount to similar types of work. Not sure what the best approach would be to injecting that static list used by these attributes would be, since the method for getting the data probably needs to "exist" (even if not really implemented) before the weaver gets there.

Another really useful way to use these static dependency graphs that might be outside the scope of this, but an interesting idea to combine it with: have you seen MS Code Contracts or PostSharp's build-time validations? Would be very interested to see if this could be used to enforce build-time rules on calling code and inheriting classes (for example, inheriting class that overrides method A must also override method B). Code Contracts is free but is also an IL Weaver and can play funny with others sometimes, but it's also limited to very specific contract requirements. PostSharp allows some very interesting types of rules to be enforced at build time which can be very useful for big teams ( http://doc.postsharp.net/custom-constraints - or, just recently I could have used this: http://doc.postsharp.net/control-implementation ). The first PostSharp example uses reflection (at build-time, during weaving, to create build errors), but I imagine if the type of dependency analysis already exists these could work well together, but I suppose it depends on how/why you get what you need for this issue. Just food for thought I suppose.

**Comment by picrap** [comment]
The initial philosophy of Mr. Advice was to stay small, and I'm still following it (not only because I'm a one-guy team, but also I see it more as a core than a full library. Other libraries may be built using Mr. Advice, but they won't be Mr. Advice).
So based on this guideline, the extra reflection added by Mr. Advice would only cover what's not covered by the .NET Framework itself. And currenlty, the big missing thing is the access to methods code (their IL body). I needed it for example to cascade dependencies notifications (I have another project, named [Mr.Advice MVVM](https://github.com/ArxOne/MrAdvice.MVVM), which could use it to automate `INotifyPropertyChanged` dependencies).
Gathering all advised methods as you suggest (which is a need I totally understand) can be made currently without changes to the core, so it means it does need to be part of it.

Regarding the build-time advices, that's an interesting direction. Currently Mr. Advice has a (very poor) weaving advising, which means your assembly can be invoked when it is weaved, to advise itself, but this is very limited for now, and I had problems with frameworks mix (Mr. Advice weaver is .NET, and thus, couldn't load weaving advices from a UWP assembly).

**Comment by TheXenocide** [comment]
I like the rationale if the core works well enough maybe I'll look into something for that once I've become more familiar with everything. The build-time stuff I think can be very valuable, and I did see some of the interfaces for it (the *Info ones, right?), it just occurs to me that it could combine well with dependency information. I'll be glad to see how the `INotifyPropertyChanged` stuff works out

**Comment by picrap** [comment]
The `*Info` interfaces are used at run-time, once per type.
It's the `IMethodWeavingAdvice` which is used at build-time; you can see a sample [here](https://github.com/ArxOne/MrAdvice.MVVM/blob/master/MrAdvice.MVVM/MVVM/ViewModel/Command.cs#L21).

**Comment by TheXenocide** [comment]
Ahh, thank you. I'll look into it more then :)

**Comment by picrap** [comment]
After thinking at it, this has nothing to do in MrAdvice, so this issue will be closed.
